---
grafana:
  image: grafana/grafana:latest
#  image: grafana/grafana:7.3.6  alternatively if we want to fix the version
  container_name: grafana
  volumes:
    - grafana_data:/var/lib/grafana # do we want to put this elsewhere?
    - ./grafana/provisioning:/etc/grafana/provisioning
  environment:
    - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - GF_USERS_ALLOW_SIGN_UP=false
  restart: unless-stopped
  expose:
    - 3000
